[2016-09-13 18:24:15,460] [ERROR] [__main__-10796.log] [device_center_client.py:_connect:585]  [connect failed]
[2016-09-13 18:24:27,076] [ERROR] [__main__-10796.log] [device_center_client.py:_connect:585]  [connect failed]
[2016-09-13 18:24:38,694] [ERROR] [__main__-10796.log] [device_center_client.py:_connect:585]  [connect failed]
